version: '3.8'
services:
  app:
    image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG}"  # Reference the Docker image and tag
    ports:
      - "8089:8089"  # Map container port 8089 to host port 8089
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Example environment variable
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

