version: '3.8'

services:
  spring:
    image: azizallani/backend-image:latest
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/kaddem
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  sonarqube:
      image: sonarqube:8.9.7-community
      ports:
        - "9000:9000"
      volumes:
        - 'SonarQube_data:/opt/sonarqube/data'
        - 'SonarQube_extensions:/opt/sonarqube/extensions'
        - 'SonarQube_logs:/opt/sonarqube/logs'
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - 'nexus-data:/nexus-data'
volumes:
  mysql_data:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
  nexus-data:
